bridge = "beny"
port = 12314
username = "AA:AA:AA:AA:AA:14"

[[services]]
type = "AccessoryInformation"

[services.characteristics]
Identify = {} # leave property completely out 'cos otherwise Homekit won't accept
Manufacturer = "Jyri-Matti Lähteenmäki"
Model = "BCP-AT1N-L"
Name = "ZJ Beny"
SerialNumber = "AA:AA:AA:AA:AA:14"
FirmwareRevision = "100.1.1"


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Latausteho"
ConfiguredName = "Latausteho"
[services.characteristics.CurrentTemperature]
minValue = 0
maxValue = 999
minStep = 0.1
cmd = "cd beny; ./cmd/charging_power.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Lataa"
ConfiguredName = "Lataa"
[services.characteristics.On]
cmd = "cd beny; ./cmd/charge.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Hybrid mode"
ConfiguredName = "Hybrid mode"
[services.characteristics.On]
cmd = "cd beny; ./cmd/mode_hybrid.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "PV mode"
ConfiguredName = "PV mode"
[services.characteristics.On]
cmd = "cd beny; ./cmd/mode_pv.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Lataa yöllä"
ConfiguredName = "Lataa yöllä"
[services.characteristics.On]
cmd = "cd beny; ./cmd/charge_next_night.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Plugged"
ConfiguredName = "Plugged"
[services.characteristics.On]
cmd = "cd beny; ./cmd/plugged.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Älylataus asetus"
ConfiguredName = "Älylataus asetus"
[services.characteristics.On]
cmd = "cd beny; ./cmd/dynamic_charge.sh"


[[services]]
type = "ContactSensor"

[services.characteristics]
Name = "Auton lataus"
ConfiguredName = "Auton lataus"
[services.characteristics.ContactSensorState]
iid = 100
value = 0


[[services]]
type = "MotionSensor"

[services.characteristics]
Name = "Auton lataus"
ConfiguredName = "Auton lataus"
[services.characteristics.MotionDetected]
iid = 101
value = false


[[services]]
type = "Door"

[services.characteristics]
Name = "Auton lataus"
ConfiguredName = "Auton lataus"
CurrentPosition = 0
TargetPosition = 0
PositionState = 2
[services.characteristics.ObstructionDetected]
iid = 102
value = false
